version: '3.7'

services:
  db:
    image: mariadb:10.4.11
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      - "MYSQL_DATABASE=pad0307"
      - "MYSQL_USER=pad0307"
      - "MYSQL_PASSWORD=wjddnd2020!!"
      - "MYSQL_ROOT_PASSWORD=wjddnd2020!!"
    ports:
      - "3306:3306"

  web:
    build:
        context: ./docker
    volumes:
      - "./projects/:/var/www/"
    depends_on:
      - db
    ports:
      - "80:80"